### ISSUE TITLE
Text Wrap Issue

### ISSUE THREAD

**Issue by drupalshift** [cdes/figma-arabic-and-rtl-support#1]
If you draw a text area so that your text gets wrapped, It will get messed up

![image](https://user-images.githubusercontent.com/9895625/62820394-03c21a00-bb79-11e9-98a5-49be74388f24.png)

**Comment by cdes** [comment]
Line wrapping is not supported because it's not possible yet to hook into Figma's wrapping algorithm.  It's a limitation of the available plugins API.

(this was mentioned in the plugin description)

Sorry, closing this.
